name: Metrics
on:
  # Schedule updates (each monday cron job)
  schedule: [{cron: "0 0 * * 1"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          plugin_lines: yes
          plugin_traffic: no
          plugin_stars: no
          plugin_stars_limit: 4
          plugin_isocalendar: no
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_languages: no
          plugin_languages_ignored: html, css, json, xml, javascript
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 0
          commits_authoring: matteias.collet@bluewin.ch, .user.login, Collet
          plugin_achievements: no
          plugin_achievements_threshold: C       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_habits: no
          plugin_habits_from: 500
          plugin_habits_days: 7
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
